model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
[projects."/Users/prateek/dotfiles"]
trust_level = "trusted"

[projects."/Users/prateek"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-03-calibre-setup"]
trust_level = "trusted"

[projects."/Users/prateek/code/literotica"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-03-crosspoint-reader-tailscale"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-04-ebook-platform-eval"]
trust_level = "trusted"

[projects."/Users/prateek/code/github.com/SillyTavern/SillyTavern"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-03-calibre-setup/serial-sync"]
trust_level = "trusted"

[projects."/Users/prateek/code/gocode/src/github.com/prateek/movies.do-reverse-engineer"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/movies.do-app"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-06-ios-silly-tavern"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-03-03-timeline-attempt"]
trust_level = "trusted"

[projects."/Users/prateek/code/experiments/2026-04-08-agent-spec-survey"]
trust_level = "trusted"

[notice.model_migrations]
gpt-5-codex = "gpt-5.3-codex"
"gpt-5.2" = "gpt-5.3-codex"

[mcp_servers.granola]
enabled = true
url = "https://mcp.granola.ai/mcp"

[features]
multi_agent = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true
