tap "1password/tap"
tap "aspnet/dnx"
tap "assemblyai/assemblyai"
tap "bazelbuild/tap"
tap "cirruslabs/cli"
tap "d12frosted/emacs-plus"
tap "dagger/tap"
tap "discoteq/discoteq"
tap "f/mcptools"
tap "facebook/fb"
tap "felixkratz/formulae"
tap "holgerbrandl/tap"
tap "hudochenkov/sshpass"
tap "mattt/tap"
tap "neovim/neovim"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "romkatv/powerlevel10k"
tap "saulpw/vd"
tap "thoughtbot/formulae"
tap "prateek/fastcp", "https://github.com/prateek/fastcp"

brew "ack"
brew "act"
brew "ansible"
brew "cairo"
brew "zstd"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "asciinema"
brew "autoconf"
brew "autojump"
brew "automake"
brew "autossh"
brew "bash"
brew "bat"
brew "bazel"
brew "berkeley-db", link: true
brew "berkeley-db@4"
brew "binutils"
brew "boost"
brew "brightness"
brew "btop"
brew "chezmoi"
brew "clang-format"
brew "cloc"
brew "isl"
brew "cloog"
brew "cmake"
brew "ripgrep"
brew "coreutils"
brew "cscope"
brew "csshx"
brew "ctags"
brew "ctop"
brew "cweb"
brew "czmq"
brew "datamash"
brew "ddcctl"
brew "dex2jar"
brew "direnv"
brew "docker"
brew "dos2unix"
brew "doxygen"
brew "e2fsprogs"
brew "nettle"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs", link: false
brew "openjpeg"
brew "leptonica"
brew "tesseract"
brew "ghostscript"
brew "extract_url"
brew "fabric-ai"
brew "fd"
brew "fdupes"
brew "libogg"
brew "libvorbis"
brew "sdl2"
brew "findutils"
brew "libtool"
brew "fontforge"
brew "fzf"
brew "forgit"
brew "fswatch"
brew "mpfr"
brew "gawk"
brew "gdrive"
brew "gh"
brew "gibo"
brew "git"
brew "gitleaks"
brew "git-review"
brew "git-revise"
brew "gitui"
brew "gl2ps"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "gpgme"
brew "gmime"
brew "gnu-sed"
brew "gnu-typist"
brew "libmaxminddb"
brew "tokyo-cabinet"
brew "goaccess"
brew "gperftools"
brew "graphicsmagick"
brew "graphviz"
brew "helix"
brew "htop"
brew "hub"
brew "hyperfine"
brew "fastcp", args: ["HEAD"]
brew "imagemagick"
brew "imagemagick@6"
brew "irssi"
brew "jq"
brew "jsonnet"
brew "lzlib"
brew "librdkafka"
brew "kcat"
brew "kubernetes-cli"
brew "lazygit"
brew "leiningen"
brew "less"
brew "libmagic"
brew "libusb-compat"
brew "libvterm"
brew "llm"
brew "lua"
brew "luajit"
brew "lynx"
brew "mas"
brew "mcpm"
brew "meson"
brew "mise"
brew "moreutils"
brew "protobuf"
brew "mosh", args: ["HEAD"]
brew "mpssh"
brew "msmtp"
brew "mycli"
brew "mysql"
brew "neovim"
brew "netcat"
brew "ngrep"
brew "nmap"
brew "talloc"
brew "ocaml-findlib"
brew "pngquant"
brew "unpaper"
brew "ocrmypdf"
brew "offlineimap"
brew "p7zip"
brew "pandoc"
brew "pbzip2"
brew "pgcli"
brew "php"
brew "pidof"
brew "pigz"
brew "plotutils"
brew "poppler"
brew "postgresql@14"
brew "pre-commit", link: false
brew "pstree"
brew "pth"
brew "pure"
brew "putty"
brew "pv"
brew "python-yq"
brew "python@3.11"
brew "qcachegrind"
brew "qscintilla2"
brew "ranger"
brew "reattach-to-user-namespace"
brew "redis"
brew "repomix"
brew "rlwrap"
brew "rsync"
brew "s3cmd"
brew "scmpuff"
brew "sdl2_image"
brew "sdl2_mixer"
brew "sdl2_ttf"
brew "shellcheck"
brew "sip"
brew "smartmontools"
brew "socat"
brew "source-highlight"
brew "ssh-copy-id", link: true
brew "st"
brew "swiftformat"
brew "swiftlint"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "tesseract-lang"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "typst"
brew "urlview"
brew "uv"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "whalebrew"
brew "winetricks"
brew "wireshark"
brew "zip"
brew "zplug"
brew "zsh"
brew "assemblyai/assemblyai/assemblyai"
brew "cirruslabs/cli/tart"
brew "d12frosted/emacs-plus/emacs-plus@28"
brew "f/mcptools/mcp"
brew "facebook/fb/idb-companion"
brew "felixkratz/formulae/borders"
brew "hudochenkov/sshpass/sshpass"
brew "oven-sh/bun/bun"

cask "1password", args: { appdir: "/Applications" }
cask "1password-cli"
cask "codex"
cask "aerospace"
cask "airflow", args: { appdir: "/Applications" }
cask "alfred", args: { appdir: "/Applications" }
cask "bartender", args: { appdir: "/Applications" }
cask "bettertouchtool"
cask "caffeine", args: { appdir: "/Applications" }
# CleanShot X is installed via Setapp after login
# cask "cleanshot"
cask "container-use"
cask "disk-inventory-x", args: { appdir: "/Applications" }
cask "fastscripts", args: { appdir: "/Applications" }
cask "font-inter"
cask "font-meslo-for-powerline"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "imcp"
cask "intellij-idea"
cask "iterm2"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "key-codes", args: { appdir: "/Applications" }
cask "launchcontrol", args: { appdir: "/Applications" }
cask "leader-key"
cask "mitmproxy"
cask "monodraw", args: { appdir: "/Applications" }
cask "moom", args: { appdir: "/Applications" }
cask "mtmr"
cask "nvalt", args: { appdir: "/Applications" }
cask "obsidian"
cask "omnigraffle", args: { appdir: "/Applications" }
cask "orbstack"
cask "prince"
cask "raycast"
cask "rescuetime", args: { appdir: "/Applications" }
cask "rocket"
cask "scrivener", args: { appdir: "/Applications" }
cask "setapp"
cask "slack"
cask "spotify", args: { appdir: "/Applications" }
cask "taskpaper", args: { appdir: "/Applications" }
cask "tuist"
cask "utm"
cask "vial"
cask "visual-studio-code"
cask "voiceink"
cask "tailscale-app"
cask "zed"
cask "zen"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Lungo", id: 1263070803
mas "MeetInOne", id: 1542778639
mas "Things", id: 904280696
mas "Xcode", id: 497799835
