#!/usr/bin/env zsh
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-${0:A:h:h}}"
tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

script="$tmp_root/modify_claude_settings.py"
current="$tmp_root/current.json"
merged="$tmp_root/merged.json"
semantic_merged="$tmp_root/semantic-merged.json"
template="$tmp_root/template.json"

chezmoi \
  --source "$REPO_ROOT/home" \
  execute-template \
  --file "$REPO_ROOT/home/.chezmoitemplates/agent-claude-plugin-settings.json.tmpl" \
  >"$template"

python3 - "$template" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1]))

assert data["_generated"].startswith(
    "Generated by .agents/skills/agent-skill-management/scripts/render-agent-plugin-marketplace."
)
PY

chezmoi \
  --source "$REPO_ROOT/home" \
  execute-template \
  --file "$REPO_ROOT/home/dot_claude/modify_private_settings.json.tmpl" \
  >"$script"
chmod +x "$script"

cat >"$current" <<'JSON'
{
  "permissions": {
    "allow": [
      "Bash(gh auth *)"
    ],
    "deny": [],
    "additionalDirectories": []
  },
  "extraKnownMarketplaces": {
    "other-market": {
      "source": {
        "source": "github",
        "repo": "example/plugins"
      }
    },
    "prateek-local": {
      "source": {
        "source": "directory",
        "path": "/tmp/old"
      }
    }
  },
  "enabledPlugins": {
    "other@other-market": true,
    "stale@prateek-local": false
  },
  "statusLine": {
    "type": "command",
    "command": "printf status"
  }
}
JSON

"$script" <"$current" >"$merged"

python3 - "$merged" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1]))

assert "_generated" not in data
assert data["permissions"]["allow"] == ["Bash(gh auth *)"]
assert data["statusLine"]["command"] == "printf status"
assert data["extraKnownMarketplaces"]["other-market"]["source"]["repo"] == "example/plugins"
local = data["extraKnownMarketplaces"]["prateek-local"]["source"]
assert local["source"] == "directory"
import os
assert local["path"] == os.path.expanduser("~/.agents/plugins")

plugins = data["enabledPlugins"]
# Reflects default_loaded in each package.toml; flip the source there if rotated.
assert plugins["design@prateek-local"] is False
assert plugins["experimental@prateek-local"] is False
assert plugins["ios@prateek-local"] is False
assert plugins["utils-human@prateek-local"] is False
assert plugins["review@prateek-local"] is True
assert plugins["utils-agent@prateek-local"] is True
# Stale @prateek-local entries persist as harmless cruft (no automatic cleanup).
assert plugins["stale@prateek-local"] is False
assert plugins["other@other-market"] is True
PY

"$script" <"$merged" >"$semantic_merged"
cmp -s "$merged" "$semantic_merged"

# Nested merge: a user-added sibling under a managed marketplace table
# survives the merge (deep-merge passes through what desired doesn't own).
nested_input="$tmp_root/nested-input.json"
nested_output="$tmp_root/nested-output.json"
python3 - "$merged" "$nested_input" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
data["extraKnownMarketplaces"]["prateek-local"]["userTag"] = "keep-me"
json.dump(data, open(sys.argv[2], "w"))
PY
"$script" <"$nested_input" >"$nested_output"
python3 - "$nested_output" <<'PY'
import json, sys, os
local = json.load(open(sys.argv[1]))["extraKnownMarketplaces"]["prateek-local"]
assert local["userTag"] == "keep-me", local
assert local["source"]["path"] == os.path.expanduser("~/.agents/plugins"), local
PY
