#!/usr/bin/env zsh
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-${0:A:h:h}}"
tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

script="$tmp_root/modify_pi_settings.py"
current="$tmp_root/current.json"
merged="$tmp_root/merged.json"
semantic_merged="$tmp_root/semantic-merged.json"
pi_plugins="$tmp_root/pi-claude-plugins.json"
claude_settings="$tmp_root/claude-plugin-settings.json"

render() {
  chezmoi --source "$REPO_ROOT/home" execute-template --file "$1"
}

render "$REPO_ROOT/home/dot_pi/agent/modify_settings.json.tmpl" >"$script"
chmod +x "$script"

cat >"$current" <<'JSON'
{
  "provider": "anthropic",
  "model": "claude-opus-4-1",
  "packages": [
    "npm:pi-cursor-sdk",
    "npm:custom-package"
  ],
  "theme": "user-owned"
}
JSON

"$script" <"$current" >"$merged"

python3 - "$merged" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1]))

assert data["provider"] == "anthropic"
assert data["model"] == "claude-opus-4-1"
assert data["theme"] == "user-owned"
assert data["npmCommand"] == ["mise", "exec", "node", "--", "npm"]

packages = data["packages"]
expected_prefix = [
    "npm:@earendil-works/pi-ai",
    "npm:@earendil-works/pi-coding-agent",
    "npm:@earendil-works/pi-tui",
    "npm:pi-claude-marketplace",
    "npm:pi-cursor-sdk",
    "npm:typebox",
]
assert packages[: len(expected_prefix)] == expected_prefix, packages
assert packages.count("npm:pi-cursor-sdk") == 1, packages
assert packages[-1] == "npm:custom-package", packages
PY

"$script" <"$merged" >"$semantic_merged"
cmp -s "$merged" "$semantic_merged"

render "$REPO_ROOT/home/dot_pi/agent/claude-plugins.json.tmpl" >"$pi_plugins"
render "$REPO_ROOT/home/.chezmoitemplates/agent-claude-plugin-settings.json.tmpl" >"$claude_settings"

python3 - "$pi_plugins" "$claude_settings" "$REPO_ROOT/home/dot_pi/agent/claude-plugins.json.tmpl" <<'PY'
import json
import os
import sys

pi_plugins = json.load(open(sys.argv[1]))
claude_settings = json.load(open(sys.argv[2]))
raw_template = open(sys.argv[3]).read()

assert pi_plugins["schemaVersion"] == 1
assert "_generated" not in pi_plugins
assert raw_template.startswith(
    "{{/* Generated by .agents/skills/agent-skill-management/scripts/render-agent-plugin-marketplace."
)

marketplace = pi_plugins["marketplaces"]["prateek-local"]
assert marketplace["source"] == os.path.expanduser("~/.agents/plugins")
assert marketplace["autoupdate"] is False

claude_enabled = claude_settings["enabledPlugins"]
pi_enabled = {
    key: value["enabled"]
    for key, value in pi_plugins["plugins"].items()
}
assert pi_enabled == claude_enabled, (pi_enabled, claude_enabled)
PY
