#!/usr/bin/env zsh
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-${0:A:h:h}}"
tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

script="$tmp_root/modify_pi_settings.py"
current="$tmp_root/current.json"
merged="$tmp_root/merged.json"
idempotent="$tmp_root/idempotent.json"
empty_in="$tmp_root/empty.json"
empty_out="$tmp_root/empty-out.json"
pi_plugins="$tmp_root/pi-claude-plugins.json"
claude_settings="$tmp_root/claude-plugin-settings.json"

render() {
  chezmoi --source "$REPO_ROOT/home" execute-template --file "$1"
}

render "$REPO_ROOT/home/dot_pi/agent/modify_settings.json.tmpl" >"$script"
chmod +x "$script"

cat >"$current" <<'JSON'
{
  "npmCommand": ["npm"],
  "packages": [
    "npm:pi-cursor-sdk",
    "npm:pi-vim",
    "npm:custom-package"
  ],
  "provider": "openai",
  "model": "gpt-5.5",
  "theme": "user-owned",
  "piVim": {
    "clipboardMirror": "all",
    "modeColors": {
      "visual": "borderStrong"
    },
    "modeChange": {
      "insert": "printf insert",
      "normal": "printf normal"
    }
  },
  "statusLine": {
    "type": "command",
    "command": "printf old"
  },
  "trust": {
    "/Users/prungta/code/worktrees/dotfiles": true
  }
}
JSON

"$script" <"$current" >"$merged"

python3 - "$merged" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1]))

assert data["provider"] == "openai"
assert data["model"] == "gpt-5.5"
assert data["theme"] == "user-owned"
assert data["npmCommand"] == ["mise", "exec", "node", "--", "npm"], data["npmCommand"]
assert data["packages"] == [
    "npm:@earendil-works/pi-ai",
    "npm:@earendil-works/pi-coding-agent",
    "npm:@earendil-works/pi-tui",
    "npm:pi-claude-marketplace",
    "npm:pi-cursor-sdk",
    "npm:typebox",
    "npm:pi-vim",
    "npm:pi-statusline",
    "npm:custom-package",
], data["packages"]
assert data["packages"].count("npm:pi-cursor-sdk") == 1, data["packages"]
assert data["packages"].count("npm:pi-vim") == 1, data["packages"]
assert data["piVim"] == {
    "clipboardMirror": "yank",
    "modeChange": {
        "insert": "printf insert",
        "normal": "printf normal",
    },
    "modeColors": {
        "visual": "borderStrong",
        "insert": "borderMuted",
        "normal": "borderAccent",
        "ex": "warning",
    },
    "syncBorderColorWithMode": True,
}, data["piVim"]
assert data["statusLine"] == {
    "type": "command",
    "command": "~/.pi/agent/statusline.sh",
    "placement": "footer",
    "debounceMs": 300,
}, data["statusLine"]
assert data["trust"]["/Users/prungta/code/worktrees/dotfiles"] is True
PY

"$script" <"$merged" >"$idempotent"
cmp -s "$merged" "$idempotent" || { echo "FAIL: merge is not idempotent" >&2; exit 1; }

: >"$empty_in"
"$script" <"$empty_in" >"$empty_out"

python3 - "$empty_out" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1]))
assert data["npmCommand"] == ["mise", "exec", "node", "--", "npm"]
assert data["packages"] == [
    "npm:@earendil-works/pi-ai",
    "npm:@earendil-works/pi-coding-agent",
    "npm:@earendil-works/pi-tui",
    "npm:pi-claude-marketplace",
    "npm:pi-cursor-sdk",
    "npm:typebox",
    "npm:pi-vim",
    "npm:pi-statusline",
]
assert data["piVim"] == {
    "clipboardMirror": "yank",
    "modeColors": {
        "insert": "borderMuted",
        "normal": "borderAccent",
        "ex": "warning",
    },
    "syncBorderColorWithMode": True,
}
assert data["statusLine"]["command"] == "~/.pi/agent/statusline.sh"
PY

render "$REPO_ROOT/home/dot_pi/agent/claude-plugins.json.tmpl" >"$pi_plugins"
render "$REPO_ROOT/home/.chezmoitemplates/agent-claude-plugin-settings.json.tmpl" >"$claude_settings"

python3 - "$pi_plugins" "$claude_settings" "$REPO_ROOT/home/dot_pi/agent/claude-plugins.json.tmpl" <<'PY'
import json
import os
import sys

pi_plugins = json.load(open(sys.argv[1]))
claude_settings = json.load(open(sys.argv[2]))
raw_template = open(sys.argv[3]).read()

assert pi_plugins["schemaVersion"] == 1
assert "_generated" not in pi_plugins
assert raw_template.startswith(
    "{{/* Generated by .agents/skills/agent-skill-management/scripts/render-agent-plugin-marketplace."
)

marketplace = pi_plugins["marketplaces"]["prateek-local"]
assert marketplace["source"] == os.path.expanduser("~/.agents/plugins")
assert marketplace["autoupdate"] is False

claude_enabled = claude_settings["enabledPlugins"]
pi_enabled = {
    key: value["enabled"]
    for key, value in pi_plugins["plugins"].items()
}
assert pi_enabled == claude_enabled, (pi_enabled, claude_enabled)
PY

echo "ok: pi settings modify (packages, plugins, pi-vim, pi statusline, passthrough, idempotence)"
