MANAGED = {
    'personal': (
        '.config/cmux/preferences.json',
        '.config/ghostty',
        'Library/Preferences/com.hegenberg.BetterTouchTool.plist',
        'Library/Preferences/com.raycast.macos.plist',
        '.config/raycast/scripts/temp-admin.sh',
        '.local/share/raycast-extensions/orca-worktree/package.json',
        'Library/Preferences/com.setapp.DesktopClient.plist',
        'Library/Preferences/pro.betterdisplay.BetterDisplay.plist',
        '.config/zed',
        '.config/tuna/config.toml',
        'Library/Preferences/com.brnbw.Tuna.plist',
        'Library/Scripts/g95-sharp.sh',
        'Library/Scripts/dayjob-password.sh',
        'Library/Scripts/temp-admin.sh',
        'Library/Application Support/orca/orca-data.json',
        '.orca/keybindings.json',
        'Library/Application Support/Code/User',
        'Library/Colors/nvALT.clr',
        'Library/Preferences/com.cmuxterm.app.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        'Library/Preferences/com.stonerl.Thaw.plist',
        'Library/Preferences/dev.kdrag0n.MacVirt.plist',
        'Library/Preferences/net.elasticthreads.nv.plist',
        '.codex/config.toml',
        '.codex/skills',
        '.config/mcporter/mcporter.json',
        '.config/mise/conf.d/mcporter.toml',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
    ),
    'work': (
        '.config/ghostty',
        'Library/Preferences/pro.betterdisplay.BetterDisplay.plist',
        '.config/zed',
        'Library/Application Support/orca/orca-data.json',
        '.orca/keybindings.json',
        'Library/Preferences/com.cmuxterm.app.plist',
        'Library/Preferences/com.setapp.DesktopClient.plist',
        'Library/Preferences/com.stonerl.Thaw.plist',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
    ),
    'homelab': (
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        '.codex/config.toml',
        '.codex/skills',
        '.config/mcporter/mcporter.json',
        '.config/mise/conf.d/mcporter.toml',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
        'Library/Preferences/com.cmuxterm.app.plist',
        'Library/Application Support/orca/orca-data.json',
        '.orca/keybindings.json',
    ),
}

UNMANAGED = {
    'personal': (
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
    ),
    'ci': (
        '.config/cmux',
        '.config/ghostty',
        'Library/Preferences/com.hegenberg.BetterTouchTool.plist',
        'Library/Preferences/com.raycast.macos.plist',
        '.config/raycast/scripts/temp-admin.sh',
        'Library/Preferences/com.setapp.DesktopClient.plist',
        'Library/Preferences/dev.kdrag0n.MacVirt.plist',
        '.config/tuna/config.toml',
        'Library/Preferences/com.brnbw.Tuna.plist',
        'Library/Application Support/Code/User',
        'Library/Preferences/pro.betterdisplay.BetterDisplay.plist',
        '.config/zed',
        'Library/Colors/nvALT.clr',
        'Library/Preferences/com.cmuxterm.app.plist',
        'Library/Application Support/orca/orca-data.json',
        '.orca/keybindings.json',
        'Library/Preferences/net.elasticthreads.nv.plist',
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        'Library/Preferences/com.stonerl.Thaw.plist',
        '.codex/config.toml',
        '.codex/skills',
        '.config/mcporter',
        '.config/mise/conf.d/mcporter.toml',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
    ),
    'work': (
        'Library/Colors/nvALT.clr',
        'Library/Preferences/net.elasticthreads.nv.plist',
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        '.codex/config.toml',
        '.codex/skills',
        '.config/mcporter',
        '.config/mise/conf.d/mcporter.toml',
    ),
    'homelab': (
        '.config/ghostty',
        'Library/Preferences/com.hegenberg.BetterTouchTool.plist',
        'Library/Preferences/com.raycast.macos.plist',
        'Library/Preferences/com.setapp.DesktopClient.plist',
        'Library/Preferences/pro.betterdisplay.BetterDisplay.plist',
        '.config/zed',
        'Library/Colors/nvALT.clr',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        'Library/Preferences/com.stonerl.Thaw.plist',
    ),
}

IGNORED = {
    'work': (
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        '.codex',
        '.config/mcporter',
        '.config/mise/conf.d/mcporter.toml',
    ),
    'homelab': (
        '.config/ghostty',
        'Library/Preferences/com.setapp.DesktopClient.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
    ),
    'ci': (
        '.config/ghostty',
        'Library/Preferences/com.hegenberg.BetterTouchTool.plist',
        'Library/Preferences/com.raycast.macos.plist',
        '.config/raycast/scripts/temp-admin.sh',
        '.config/tuna/config.toml',
        'Library/Preferences/com.brnbw.Tuna.plist',
        'Library/Scripts/g95-sharp.sh',
        'Library/Scripts/dayjob-password.sh',
        'Library/Scripts/temp-admin.sh',
        'Library/Application Support/Code/User',
        '.config/zed',
        '.config/cmux',
        'Library/Application Support/orca/orca-data.json',
        '.orca/keybindings.json',
        'Library/Colors/nvALT.clr',
        'Library/Preferences/com.cmuxterm.app.plist',
        'Library/Preferences/net.elasticthreads.nv.plist',
        'Library/Preferences/pro.betterdisplay.BetterDisplay.plist',
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        'Library/Preferences/com.stonerl.Thaw.plist',
        '.codex',
        '.config/mcporter',
        '.config/mise/conf.d/mcporter.toml',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
    ),
    'empty': (
        '.codex',
        '.config/mcporter',
        '.config/mise/conf.d/mcporter.toml',
        '.config/qmd/wiki-agent-sessions.yml',
        '.local/bin/wiki-sessions-sync',
        '.config/tuna/config.toml',
        'Library/Preferences/com.brnbw.Tuna.plist',
        'Library/Application Support/orca/orca-data.json',
        '.config/ghostty',
        'Library/Application Support/Code/User',
        'Library/Preferences/dev.kdrag0n.MacVirt.plist',
        'Library/Preferences/com.prakashjoshipax.VoiceInk.plist',
        'Library/Preferences/com.hegenberg.BetterTouchTool.plist',
        'Library/Preferences/com.raycast.macos.plist',
        '.config/raycast/scripts/temp-admin.sh',
        '.local/share/raycast-extensions',
        'Library/Preferences/io.tailscale.ipn.macsys.plist',
        'Library/Preferences/com.setapp.DesktopClient.plist',
    ),
}
