[packages]
default_machine_type = "personal"

[packages.groups.base]
description = "Essentials on every machine"
taps  = [{ name = "fluffypony/yojam" }]
casks = [{ name = "yojam" }]

[packages.machine_types.personal]
groups = ["base"]
