# Target paths (relative to $HOME) of license files materialized via
# secret-backed chezmoi templates, keyed by their ref name in
# home/.chezmoidata/secrets.toml > [secrets.refs]. .chezmoiignore skips a
# path unless secrets_enabled=true and its ref is set.
#
# Verify paths on first `chezmoi apply --dry-run`. App publishers
# occasionally relocate license files between major versions.
[licenses.paths]
bettertouchtool_license = "Library/Application Support/BetterTouchTool/bettertouchtool.bttlicense"
moom_license = "Library/Application Support/Many Tricks/Licenses/Moom.moomcombolicense"
alfred_license = "Library/Application Support/Alfred/License/Alfred.alfredlicense"
