import json

from tests.support.python import ROOT, RepoTestCase


class PiConfigTests(RepoTestCase):
    packages = [
        "npm:@earendil-works/pi-ai", "npm:@earendil-works/pi-coding-agent", "npm:@earendil-works/pi-tui",
        "npm:pi-claude-marketplace", "npm:pi-cursor-sdk", "npm:typebox", "npm:pi-vim", "npm:pi-statusline",
    ]
    vim = {"clipboardMirror": "yank", "modeColors": {"insert": "borderMuted", "normal": "borderAccent", "ex": "warning"},
           "syncBorderColorWithMode": True}
    statusline = {"type": "command", "command": "~/.pi/agent/statusline.sh", "placement": "footer", "debounceMs": 300}

    def test_dependency_order_and_nested_merge_preserve_user_preferences(self):
        modify = self.modifier("home/dot_pi/agent/modify_settings.json.tmpl")
        current = {
            "npmCommand": ["npm"], "packages": ["npm:pi-cursor-sdk", "npm:pi-vim", "npm:custom-package"],
            "provider": "openai", "model": "user-model", "theme": "user-owned",
            "piVim": {"clipboardMirror": "all", "modeColors": {"visual": "borderStrong"},
                      "modeChange": {"insert": "printf insert", "normal": "printf normal"}},
            "statusLine": {"type": "command", "command": "printf old"}, "trust": {"/code/worktree": True},
        }
        result = self.command(modify, json.dumps(current).encode())
        expected = current | {
            "npmCommand": ["mise", "exec", "node", "--", "npm"], "packages": self.packages + ["npm:custom-package"],
            "piVim": self.vim | {"modeColors": self.vim["modeColors"] | {"visual": "borderStrong"},
                                 "modeChange": current["piVim"]["modeChange"]},
            "statusLine": self.statusline,
        }
        self.assertEqual(json.loads(result.stdout), expected)
        self.assertIs(json.loads(result.stdout)["trust"]["/code/worktree"], True)
        self.assertEqual(self.command(modify, result.stdout).stdout, result.stdout)

    def test_empty_config_gets_only_managed_package_and_renderer_settings(self):
        result = self.command(self.modifier("home/dot_pi/agent/modify_settings.json.tmpl"))
        self.assertEqual(json.loads(result.stdout), {
            "npmCommand": ["mise", "exec", "node", "--", "npm"], "packages": self.packages,
            "piVim": self.vim, "statusLine": self.statusline,
        })

    def test_marketplace_schema_and_enable_policy_match_claude(self):
        path = "home/dot_pi/agent/claude-plugins.json.tmpl"
        pi = json.loads(self.render(path))
        claude = json.loads(self.render("home/.chezmoitemplates/agent-claude-plugin-settings.json.tmpl"))
        self.assertEqual(pi["schemaVersion"], 1)
        self.assertNotIn("_generated", pi)
        self.assertTrue((ROOT / path).read_text().startswith(
            "{{/* Generated by .agents/skills/agent-skill-management/scripts/render-agent-plugin-marketplace."))
        self.assertEqual(pi["marketplaces"]["prateek-local"]["source"], str(self.home / ".agents/plugins"))
        self.assertIs(pi["marketplaces"]["prateek-local"]["autoupdate"], False)
        self.assertEqual({key: value["enabled"] for key, value in pi["plugins"].items()}, claude["enabledPlugins"])
