{
  # Mirror of the former home/.chezmoidata/packages.toml. Profiles share keys;
  # nix lazy-eval ensures only the selected profile is realised.
  #
  # When updating, keep entries sorted within their category and prefer plain
  # strings for items with no extra args (terser).
  profiles = {
    core = {
      description = "Core package set";
      taps = [
        "1password/tap"
        "felixkratz/formulae"
        "fluffypony/yojam"
      ];
      brews = [
        "direnv"
        "fd"
        "felixkratz/formulae/borders"
        "fzf"
        "zoxide"
        "gh"
        { name = "git"; link = false; }
        "gitleaks"
        "git-spice"
        "kanata"
        "libpq"
        "llm"
        "mise"
        "neovim"
        "ripgrep"
        "uv"
        "shellcheck"
        "tmux"
        "worktrunk"
      ];
      casks = [
        "codex"
        { name = "1password"; appdir = "/Applications"; }
        "1password-cli"
        { name = "alfred"; appdir = "/Applications"; }
        "bettertouchtool"
        "font-hack-nerd-font"
        "font-jetbrains-mono"
        "ghostty"
        "iterm2"
        "google-chrome"
        "karabiner-elements"
        "leader-key"
        { name = "moom"; appdir = "/Applications"; }
        "orbstack"
        "raycast"
        "setapp"
        "tailscale-app"
        "visual-studio-code"
        "voiceink"
        "yojam"
      ];
      mas = [ ];
      ghExtensions = [ "enthus-appdev/gh-attach" ];
      disabledCasks = [
        { name = "cleanshot"; reason = "Optional: CleanShot X (often licensed/installed via Setapp)"; }
      ];
    };

    full = {
      description = "Full package set";
      taps = [
        "1password/tap"
        "aspnet/dnx"
        "bazelbuild/tap"
        "cirruslabs/cli"
        "dagger/tap"
        "discoteq/discoteq"
        "eugene1g/safehouse"
        "f/mcptools"
        "facebook/fb"
        "felixkratz/formulae"
        "fluffypony/yojam"
        "go-delve/delve"
        "hashicorp/tap"
        "holgerbrandl/tap"
        "hudochenkov/sshpass"
        "juxt/allium"
        "manaflow-ai/cmux"
        "mattt/tap"
        "neovim/neovim"
        "nikitabobko/tap"
        "oven-sh/bun"
        "peripheryapp/periphery"
        "prateek/tap"
        "romkatv/powerlevel10k"
        "saulpw/vd"
        "steipete/tap"
        "thoughtbot/formulae"
      ];
      brews = [
        "ack"
        "act"
        "actionlint"
        "aria2"
        "cairo"
        "zstd"
        "libtiff"
        "little-cms2"
        "webp"
        "asciinema"
        "autoconf"
        "zoxide"
        "automake"
        "bash"
        "bat"
        "bazel"
        "binutils"
        "boost"
        "brightness"
        "btop"
        "buildifier"
        "clang-format"
        "cloc"
        "isl"
        "cloog"
        "cmake"
        "ripgrep"
        "coreutils"
        "cscope"
        "csshx"
        "ctags"
        "ctop"
        "cweb"
        "czmq"
        "datamash"
        "ddcctl"
        "direnv"
        "docker"
        "dos2unix"
        "doxygen"
        "e2fsprogs"
        "eugene1g/safehouse/agent-safehouse"
        "nettle"
        "p11-kit"
        "unbound"
        "gnutls"
        "openjpeg"
        "leptonica"
        "tesseract"
        "ghostscript"
        "codex-acp"
        "extract_url"
        "fabric-ai"
        "fastlane"
        "fd"
        "fdupes"
        "libogg"
        "libvorbis"
        "sdl2"
        "findutils"
        "libtool"
        "fontforge"
        "fzf"
        "forgit"
        "fswatch"
        "fennel"
        "mpfr"
        "gawk"
        "gdrive"
        "gh"
        "gibo"
        { name = "git"; link = false; }
        "git-delta"
        "gitleaks"
        "git-review"
        "git-revise"
        "git-spice"
        "git-subrepo"
        "gitui"
        "gl2ps"
        "libgpg-error"
        "libassuan"
        "libgcrypt"
        "libksba"
        "libusb"
        "pinentry"
        "gnupg"
        "gpgme"
        "gmime"
        "gnu-sed"
        "gnu-typist"
        "libmaxminddb"
        "tokyo-cabinet"
        "go"
        "goaccess"
        "gogcli"
        "gperftools"
        "graphicsmagick"
        "graphviz"
        "helix"
        "htop"
        "tmux"
        "hub"
        "hyperfine"
        "imagemagick"
        "imagemagick@6"
        "irssi"
        "jq"
        "jsonnet"
        "juxt/allium/allium"
        "lzlib"
        "librdkafka"
        "kanata"
        "kcat"
        "kubernetes-cli"
        "lazygit"
        "leiningen"
        "less"
        "libmagic"
        "libpq"
        "libusb-compat"
        "libvterm"
        "llm"
        "lua"
        "luajit"
        "lynx"
        "mackup"
        "mas"
        "mcpm"
        "meson"
        "mise"
        "moreutils"
        "protobuf"
        "mosh"
        "mpssh"
        "msmtp"
        "mycli"
        "mysql"
        "neovim"
        "netcat"
        "ngrep"
        "nmap"
        "talloc"
        "ocaml-findlib"
        "pngquant"
        "unpaper"
        "ocrmypdf"
        "offlineimap"
        "openjdk"
        "p7zip"
        "pandoc"
        "pbzip2"
        "pgcli"
        "pigz"
        "plotutils"
        "poppler"
        "prek"
        "pstree"
        "pth"
        "pure"
        "pv"
        "prateek/tap/agentsview"
        "python-yq"
        "python@3.11"
        "qcachegrind"
        "qscintilla2"
        "ranger"
        "reattach-to-user-namespace"
        "redis"
        "repomix"
        "rlwrap"
        "rsync"
        "s3cmd"
        "scmpuff"
        "sdl2_image"
        "sdl2_mixer"
        "shellcheck"
        "sip"
        "smartmontools"
        "socat"
        { name = "ssh-copy-id"; link = true; }
        "st"
        "swiftformat"
        "telnet"
        "terminal-notifier"
        "hashicorp/tap/terraform"
        "the_silver_searcher"
        "tig"
        "tree"
        "typst"
        "urlview"
        "uv"
        "vim"
        "watch"
        "watchman"
        "wget"
        "winetricks"
        "wireshark"
        "worktrunk"
        "xcbeautify"
        { name = "homebrew/core/xcodes"; args = [ "force-bottle" ]; }
        "xcodegen"
        "zig"
        "zip"
        "zplug"
        "zsh"
        "cirruslabs/cli/tart"
        "f/mcptools/mcp"
        "felixkratz/formulae/borders"
        "hudochenkov/sshpass/sshpass"
        "oven-sh/bun/bun"
      ];
      casks = [
        { name = "1password"; appdir = "/Applications"; }
        "1password-cli"
        "codex"
        "aerospace"
        { name = "alfred"; appdir = "/Applications"; }
        "agentsview-desktop"
        { name = "arq"; appdir = "/Applications"; }
        "betterdisplay"
        "bettertouchtool"
        { name = "caffeine"; appdir = "/Applications"; }
        "claude"
        "cmux"
        "container-use"
        "codexbar"
        { name = "fastscripts"; appdir = "/Applications"; }
        "font-inter"
        "font-meslo-for-powerline"
        "font-hack-nerd-font"
        "font-jetbrains-mono"
        "font-jetbrains-mono-nerd-font"
        "gcloud-cli"
        "ghostty"
        "google-drive"
        { name = "hammerspoon"; appdir = "/Applications"; }
        "google-chrome"
        "imcp"
        "iterm2"
        "jordanbaird-ice"
        "karabiner-elements"
        { name = "key-codes"; appdir = "/Applications"; }
        { name = "launchcontrol"; appdir = "/Applications"; }
        "leader-key"
        "mitmproxy"
        { name = "monodraw"; appdir = "/Applications"; }
        { name = "moom"; appdir = "/Applications"; }
        { name = "nvalt"; appdir = "/Applications"; }
        "obsidian"
        "ollama-app"
        "orbstack"
        "periphery"
        "raycast"
        { name = "rescuetime"; appdir = "/Applications"; }
        "rocket"
        { name = "scrivener"; appdir = "/Applications"; }
        "setapp"
        "slack"
        { name = "spotify"; appdir = "/Applications"; }
        "superset"
        { name = "taskpaper"; appdir = "/Applications"; }
        "tuist"
        "utm"
        "visual-studio-code"
        "vlc"
        "voiceink"
        "xquartz"
        "tailscale-app"
        "yojam"
        "zed"
      ];
      mas = [
        { name = "1Password for Safari"; id = 1569813296; }
        { name = "Amphetamine"; id = 937984704; }
        { name = "Goodnotes"; id = 1444383602; }
        { name = "Lungo"; id = 1263070803; }
        { name = "Okta Verify"; id = 490179405; }
        { name = "Things"; id = 904280696; }
      ];
      xcodeRequiredBrews = [
        "facebook/fb/idb-companion"
        "swiftlint"
      ];
      ghExtensions = [ "enthus-appdev/gh-attach" ];
      disabledCasks = [
        { name = "cleanshot"; reason = "CleanShot X is installed via Setapp after login"; }
        { name = "mtmr"; reason = "Upstream cask download fails TLS negotiation from fresh macOS guests"; }
      ];
    };
  };
}
